/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AchanModal {
        "callIcon": string;
        "carIcon": string;
        "id": string;
        "opened": boolean;
        "previousBtn": string;
        "whatappIcon": string;
    }
    interface ModalBookingDetails {
        "airport": string;
        "date": string | number;
        "destination": string;
        "destinationAddress": string;
        "dottedLines": string;
        "estimatedPriceMax": string | number;
        "estimatedPriceMin": string | number;
        "time": string | number;
    }
    interface ModalBotton {
        "externalbtn": string;
        "id": string;
    }
    interface OneWayContent {
        "onBookChange": () => void;
    }
    interface RowElement {
    }
}
declare global {
    interface HTMLAchanModalElement extends Components.AchanModal, HTMLStencilElement {
    }
    var HTMLAchanModalElement: {
        prototype: HTMLAchanModalElement;
        new (): HTMLAchanModalElement;
    };
    interface HTMLModalBookingDetailsElement extends Components.ModalBookingDetails, HTMLStencilElement {
    }
    var HTMLModalBookingDetailsElement: {
        prototype: HTMLModalBookingDetailsElement;
        new (): HTMLModalBookingDetailsElement;
    };
    interface HTMLModalBottonElement extends Components.ModalBotton, HTMLStencilElement {
    }
    var HTMLModalBottonElement: {
        prototype: HTMLModalBottonElement;
        new (): HTMLModalBottonElement;
    };
    interface HTMLOneWayContentElement extends Components.OneWayContent, HTMLStencilElement {
    }
    var HTMLOneWayContentElement: {
        prototype: HTMLOneWayContentElement;
        new (): HTMLOneWayContentElement;
    };
    interface HTMLRowElementElement extends Components.RowElement, HTMLStencilElement {
    }
    var HTMLRowElementElement: {
        prototype: HTMLRowElementElement;
        new (): HTMLRowElementElement;
    };
    interface HTMLElementTagNameMap {
        "achan-modal": HTMLAchanModalElement;
        "modal-booking-details": HTMLModalBookingDetailsElement;
        "modal-botton": HTMLModalBottonElement;
        "one-way-content": HTMLOneWayContentElement;
        "row-element": HTMLRowElementElement;
    }
}
declare namespace LocalJSX {
    interface AchanModal {
        "callIcon"?: string;
        "carIcon"?: string;
        "id"?: string;
        "opened"?: boolean;
        "previousBtn"?: string;
        "whatappIcon"?: string;
    }
    interface ModalBookingDetails {
        "airport"?: string;
        "date"?: string | number;
        "destination"?: string;
        "destinationAddress"?: string;
        "dottedLines"?: string;
        "estimatedPriceMax"?: string | number;
        "estimatedPriceMin"?: string | number;
        "time"?: string | number;
    }
    interface ModalBotton {
        "externalbtn"?: string;
        "id"?: string;
    }
    interface OneWayContent {
        "onBookChange"?: () => void;
    }
    interface RowElement {
    }
    interface IntrinsicElements {
        "achan-modal": AchanModal;
        "modal-booking-details": ModalBookingDetails;
        "modal-botton": ModalBotton;
        "one-way-content": OneWayContent;
        "row-element": RowElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "achan-modal": LocalJSX.AchanModal & JSXBase.HTMLAttributes<HTMLAchanModalElement>;
            "modal-booking-details": LocalJSX.ModalBookingDetails & JSXBase.HTMLAttributes<HTMLModalBookingDetailsElement>;
            "modal-botton": LocalJSX.ModalBotton & JSXBase.HTMLAttributes<HTMLModalBottonElement>;
            "one-way-content": LocalJSX.OneWayContent & JSXBase.HTMLAttributes<HTMLOneWayContentElement>;
            "row-element": LocalJSX.RowElement & JSXBase.HTMLAttributes<HTMLRowElementElement>;
        }
    }
}
