/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AchanModal {
        "opened": boolean;
        "previousBtn": string;
    }
    interface ModalBookingDetails {
        "date1": string | number;
        "date2": string | number;
        "dottedLines": string;
        "estimatedPrice": number;
        "from": string;
        "location1": string;
        "location2": string;
        "time1": string | number;
        "time2": string | number;
    }
}
declare global {
    interface HTMLAchanModalElement extends Components.AchanModal, HTMLStencilElement {
    }
    var HTMLAchanModalElement: {
        prototype: HTMLAchanModalElement;
        new (): HTMLAchanModalElement;
    };
    interface HTMLModalBookingDetailsElement extends Components.ModalBookingDetails, HTMLStencilElement {
    }
    var HTMLModalBookingDetailsElement: {
        prototype: HTMLModalBookingDetailsElement;
        new (): HTMLModalBookingDetailsElement;
    };
    interface HTMLElementTagNameMap {
        "achan-modal": HTMLAchanModalElement;
        "modal-booking-details": HTMLModalBookingDetailsElement;
    }
}
declare namespace LocalJSX {
    interface AchanModal {
        "opened"?: boolean;
        "previousBtn"?: string;
    }
    interface ModalBookingDetails {
        "date1"?: string | number;
        "date2"?: string | number;
        "dottedLines"?: string;
        "estimatedPrice"?: number;
        "from"?: string;
        "location1"?: string;
        "location2"?: string;
        "time1"?: string | number;
        "time2"?: string | number;
    }
    interface IntrinsicElements {
        "achan-modal": AchanModal;
        "modal-booking-details": ModalBookingDetails;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "achan-modal": LocalJSX.AchanModal & JSXBase.HTMLAttributes<HTMLAchanModalElement>;
            "modal-booking-details": LocalJSX.ModalBookingDetails & JSXBase.HTMLAttributes<HTMLModalBookingDetailsElement>;
        }
    }
}
