/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AchanModal {
        "opened": boolean;
    }
}
declare global {
    interface HTMLAchanModalElement extends Components.AchanModal, HTMLStencilElement {
    }
    var HTMLAchanModalElement: {
        prototype: HTMLAchanModalElement;
        new (): HTMLAchanModalElement;
    };
    interface HTMLElementTagNameMap {
        "achan-modal": HTMLAchanModalElement;
    }
}
declare namespace LocalJSX {
    interface AchanModal {
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "achan-modal": AchanModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "achan-modal": LocalJSX.AchanModal & JSXBase.HTMLAttributes<HTMLAchanModalElement>;
        }
    }
}
